import { NeuralNetworkGPU, NeuralNetwork } from 'brain.js'

const xorTrainingData = [
    {
        "input": "Supercraptastic slasher fare, which feels overly long at 80 minutes. Years ago, a bunch of \"gypsies\" who lived in the caves of a mountain, were burned up in a forest fire. Years later, campers are going missing from the area of the fire. A bunch of horny kids are, of course, en route to this area for a debaucherous camping trip of there own. Despite an ominous welcome from the forest ranger (Jackson Bostwick) the kids troop up to the mountain any way. Before long, the kids start to get picked off by the monster, who remains unseen to the very end of the movie, probably because the makeup was so embarrassingly bad. No surprises to speak of",
        "output": "negative"
    },
    {
        "input": "Even by the lowered standards of '80s slasher movies, this one stinks. The usual gaggle of oversexed teens heads for a \"forbidden\" part of forest, which burned in the 1940s and apparently left a sole angry survivor. Fast forward (actually, you'll want to fast-forward through much of this mess) to the present day, where a couple of campers are butchered; the teens follow in their wake, while a semi-concerned park ranger (a sleepwalking Jackie Coogan) and his healthier cohort (who spins a lot of time tuning his banjo) succeed partially in steering our attention from yards of run-of-the-mill nature-footage padding. Finally, more killings--but nothing you haven't seen a zillion times before. If you want to see the kids butchered, opt for SLEEPAWAY CAMP or the first FRIDAY THE 13TH over this",
        "output": "negative"
    },
    {
        "input": "Foolish hikers go camping in the Utah mountains only to run into a murderous, disfigured gypsy. <br \/><br \/>The Prey is a pretty run of the mill slasher film, that mostly suffers from a lack of imagination. The victim characters are all-too-familiar idiot teens which means one doesn't really care about them, we just wonder when they will die! Not to mention it has one too many cheesy moments and is padded with endless, unnecessary nature footage. However it does have a few moments of interest to slasher fans, the occasional touch of spooky atmosphere, and a decent music score by Don Peake. Still, it's business as usual for dead-camper movies.<br \/><br \/>There are much better films in this vein, but over all The Prey may be watchable enough for die-hard slasher fans. Although one might be more rewarded to watch Just Before Dawn (1981), Wrong Turn (2003), or even The Final Terror (1983) again.<br \/><br \/>* 1\/2 out of ****",
        "output": "negative"
    },
    {
        "input": "Rented 3 bad movies to watch with my friends in my dorm room.<br \/><br \/>Leprechaun 4, Jack Frost and The Prey.<br \/><br \/>I picked up Jack and Lep 4 because they are well known bad movies I have never seen.<br \/><br \/>I picked this movie out because it matched the \"How to find a bad movie\" guide on badmovies.org, No real description, no pics of the movie on the back, and I had never heard of it, had to be a winner ",
        "output": "negative"
    },
    {
        "input": "I was pulled into this movie early on, much to my surprise, because I hadn't intended to watch it at all. Now I wish I hadn't. The suspense starts out well, with the hit-and-run resulting in death and the question of whether the guilty character will confess, or be found out, or (doable now, though a no-no in the old days of movie-making) get away with it. The plot's been done before--what plot hasn't--but the tensions inherent in it, with the additional complications and motivations arising out of the illicit love affair, make for an absorbing first half. Then the film abandons the hit-and-run to embark upon a misty exposition of two unrequited, all-suffering loves. The two tracks of plot--hit-and-run and unreasoning love--just don't have enough to do with each other, and that they involve the same characters doesn't bind them enough to justify the departure from the original story line. The screenwriter should have chosen one plot or the other. At the end of the film, in the midst of the movie's second funeral, I found myself thinking, \"Now, what does any of this have to do with that hit-and-run?\" The filmmakers may think the answer obvious, but I think the movie was plotted and executed flabbily.",
        "output": "negative"
    },
    {
        "input": "The prey has an interesting history, unless you remember the ads for it in newspapers in June of 1984 you might have caught it on the Movie channel back in summer 85, but little else is remembered. The plot is your basic killer in the woods again. But ironically this was filmed before Friday the 13th. The prey was actually shot sometime in 1978 according to one of the actors in an interview years later. But released for about a week at some drive ins, (yes Jim, namans drive in showed this in June of 84). But it has a dated look to it. Maybe they released it so later on to cash in on all the other terror films the market was flooded with by 1984. Now on the story, it has some kind of back story, a forest fire back in the 1940's leaves a lot of Gypsies burned to death. But one of their children survive (our monster) so flash forward to present day which would be 1978, we have an older middle age couple camping only to be dispatched by the Monster. The tag line for this picture claims ITS NOT HUMAN, AND ITS GOT AN AXE, but an Axe was only used in these first two killings. Now we have a bunch of teenagers who look like they in their mid 20's camping. We all know they are the Prey, and the monster knocks them of one by one. For an 80 minute movie it seems longer. We also have a lot of wildlife footage to fill in voids for the 80 mins. Overall for being out into an 80-'s horror movie it looks way more 70's than ever. Hey the Prey had potential to be a good horror killer in the woods movie but falls a little short.. It does however feature a pretty scary cool looking monster at the end, and we have to wait till the last 2 minutes to see him. Side note, the monster has gone on to star in the Addams family movies in the 1990's..",
        "output": "negative"
    },
    {
        "input": "All the criticisms of this movie are quite valid! It is pretty boring, and filled with all kinds of pointless ridiculous stuff. A couple exchanging nods over their \"good grub.\" A medium shot of a desk as a phone rings until someone finally comes, sits down, and answers it at a pretty leisurely pace. Quadruple-takes or more when people look at things. Solitary banjo-tuning and playing, taking a break for a beer. Telling a joke to a fawn, about a big-mouthed frog trying to learn what to feed its babies, complete with many big-mouthed expressions (which are needed for the weak punchline). The sharing of cucumber and cream cheese sandwiches on oatmeal bread, which to the squeamish become unpalatable when there's talk of people burned in a fire. Lots of seemingly stock-footage close-up shots of animals, birds, insects, and spiders in the woods.<br \/><br \/>The movie starts with a forest fire, then at least a couple decades later some people in those same woods get killed by an axe. The killer evidently wasn't too satisfied by the axe he stole, and kills other people with other weapons of opportunity or his bare hands.<br \/><br \/>If it's true that the movie in the version available on the out-of-print videotape is cut, perhaps if there's a lot of footage that was cut, it deserves another look on DVD. Otherwise, it's simply not very interesting, and would probably try the patience of even the most hardcore outdoors-slasher fan.",
        "output": "negative"
    },
    {
        "input": "I walked into a book store in Brentwood, Tennessee. I am not going to say the name because I am a dedicated customer. I have been satisfied with every item I purchased there before this one. On display in the front of the store was The Bell Witch Haunting. (Might I mention this is the only store I have seen it for sale in.) I had heard about the story somewhere and remembered it was supposed to have really happened for real. I was very excited and couldn't wait to watch it. I had great expectations for it. I couldn't believe what I seen when I viewed it. It didn't look like a real movie. It looked like a home video. I was under the impression it was suppose to be a horror movie. I mean the movie was suppose to be about a witch haunting you know. This is no horror movie. You will not jump out of your seat watching this movie. I gave the movie all the chances in the world to get better as it went along. I swear I did. It never did get any better. There were several scenes of this little kid getting poop and pee thrown on him. I didn't find that entertaining at all. I watched the whole movie with disbelief that the store would actually sell this to me. I guess that is how bad this economy has got. I have this to say to the cast and crew. Do not show this film as material to get other film jobs. Don't do it. I mean that sincerely. I commend you for trying. For people who have bought this. I say this. Don't sell your copy to someone. They could get very upset. Have a nice day everyone.",
        "output": "negative"
    },
    {
        "input": "Thank God I didn't buy this movie myself! I borrowed it from a friend who bought it out of sheer curiosity and of course after viewing it feel they should be reimbursed! This has got to be one of THE worse movies I've EVER seen! I do realize they couldn't have had much of a budget but I swear I could make a better movie than this staring my pets! The acting was horrible, so was the editing, the dialogue, EVERYTHING! It was so bad that it was seriously making me angry as I watched it! I'm looking forward to the REAL movie about this story coming out soon so that people curious about it don't have to stoop to watch this joke!",
        "output": "negative"
    },
    {
        "input": "I saw this movie with my girlfriend. It was a total disaster. You can really see it was cheaply made. Badly scripted and with very bad acting. I have read several versions of the book by different authors and also listened to one version on audio book. We couldn't take the movie seriously because of the lacking elements it should have contained. The experience of watching this was like The Blair Witch visits Green Acres. Then there were parts that were vulgar. They show this little boy using a bed pan and they actually show the contents of it. The witch throws the contents of it on the boy and the whole family laughs. I thought it was nasty and very strange. I really can't understand why someone would think that would be entertaining. It shows another scene where Dr. Mize arrives and Betsy Bell is urinating in her dress on the steps of their house in front of her mother and brothers. Instead of the mother leading her off it is the brother. How sick? The little boy in the first scene of the many scenes dealing with how your body disposes of wastes begs for toilet paper and goes to the out house and makes these sickening faces of joy with sound effects. I think they should have left all of that out. The makeup on the Reverend James Johnston as a older man didn't really make you assume he was older. It made you think he was dipped in fish batter. The blood on Joshua Gardner when he falls from the ladder is even worse. The John Bell death scene looks like they got out flour and tried to do something with it to make him look as a serious sick man. To me to much sickening comedy with bathroom problems and inexperienced people involved was the downfall of this picture. These people would do better if they film commercials for local TV Stations for bathroom products. They chose a good subject and were unable to produce it in a correct manner. I rate this film Capital F minus.",
        "output": "negative"
    },
    {
        "input": "If anyone tells you this picture is just terrific they probably have something to do with either making it or profiting from it. This film is a real loser and it copies situations from big budget horror movies and not to mention soundtracks to. I wouldn't recommend this one to my worst enemy. It is a low budget movie with amateur actors. It looks like it was filmed for a film contest. The acting is terrible and it wouldn't surprise me if the script was written by a Hee Haw script writer. My family laughed at it. A Grade ZZZZZZZZZZZZZ all the way. You won't be scared by this one. Here is one little taste of the terrible elements of this film. When the guy gets his toe stomped by Ric White's stupid portrayal of the Reverend James Johnston walking cane. The guys reactions are like if he had an amputation with no pain killer. Watch the DVD extras after you watch the movie. When you see Ric White and others talk so seriously about the movie you will laugh till your stomach hurts. How people will stretch the truth and what they will do to earn a dishonest buck. Don't get fooled like we did and buy this failure.",
        "output": "negative"
    },
    {
        "input": "Are you kidding me? This is quite possibly the worst, amateur movie I've ever seen. The casting was horrible, the acting was worse than horrible and I'm sorry, the guy at the picnic speed loading his plate full of food was somewhere near pointless and the demonic turd and chamber pot chasing Drew around was nothing more than comical. When I herd about the Bell Witch, I wanted to believe. I read some literature on it and thought it sounded like it was possible a plausible story. But this movie just destroyed that. Ric White (Director, Writer, Lead Actor, etc) takes himself a bit too seriously and I think he gives himself a little more credit than he deserves....Do yourself a favor....skip this one.",
        "output": "negative"
    },
    {
        "input": "In addition to the fact that this is just an abysmally made film (imagine giving a camcorder to the average high school drama club) the people who think that there is anything \"real\" about this legend need to grow up. This is the 21st century. Guess what",
        "output": "negative"
    },
    {
        "input": "I wanted to like this movie. I really, really did. I was so excited when I saw the preview, which scared the hell out of me. But when I saw the actual film, I was disappointed. The acting is stilted, and the attempts at comedy are woefully out of place and forced. And I'm sorry, but a boy being chased by a turd in a bedpan is not funny or scary, it's just stupid. I grew up on the Bell Witch legend, so I know quite a bit about it. A lot of facts in the movie are right on target, but this film should have been much better. The entire birthday party scene, for example, lasts about fifteen minutes, adds nothing to the plot or the story, and should have been left on the cutting room floor. A more heavy-handed editor might have been able to get a decent film out of this mess.<br \/><br \/>Please understand, I'm not in any way, shape or form involved with the other Bell Witch movie, and I'm not trying to \"attack\" this IMDb listing. I'm just telling it like it is.",
        "output": "negative"
    },
    {
        "input": "I am not understanding why people are praising this movie. I didn't like it at all. I watch it with several people. None of them cared for it either. First of all. It is just plain that another low budget studio is trying to cash in on a big name story. The actual filming looks like a live TV interview. The makeup is bad. When you watch the movie along with the DVD extras. You will see there is a lot of enthusiasm from the people who participated in it. There is no talent. There are facts that do appear in the book. The facts are distorted by the invention of comedy and skits added to it. I have read several books and have watched several shows on this story. What I have always caught from all the material on this is that it was a serious horror story. I really wish someone could really do a good film on this one. It has always fascinated me. The bad acting really ruined the story. The little boys situation really hammed it up even more. When you watch this movie. The little boy and his problem is the thing you and your friends will remember and laugh about. It didn't make any sense why his brothers were laughing at what had happened to him. It was like the witch was supposed to be so threatening but it was OK to throw baby brother to her. It is a whopping tale with him and his little problem. I can't still get over the little girl saying \"Mom said tobacco will rot your teeth.\" Frank Fox's statement and facial expression is so bad. The scene out in the yard with him getting food is pretty stupid to. The sound from parts of it seems to be from the movie psycho. Also, The girl hovering over the bed and her little \"Bladder control problem\" are from The Exorcist. This movie is lacking from the talent of creativity. We put the movie in for a couple of minutes and knew right away it was a bummer. I also noticed that their was defects in the film quality. Parts of it looked like what a person might film on a Home video camera. I noticed a lot of the people in the credits had many multiple jobs. This is probably how this movie was put together. Someone said I like this story. I will get all my friends and make a movie about with a video camera and a computer. Doesn't matter if we don't know how to act. As long as we get it on film and say it is good. We got the family together and prepared food. Then sat down and watched this failed attempt to make a movie.",
        "output": "negative"
    },
    {
        "input": "This tale of the upper-classes getting their come-uppance and wallowing in their high-class misery is like a contemporary Mid-Sommerish version of an old Joan Crawford movie in which she suffered in mink. Here, people behave in a frightfully civilized manner in the face of adversity. A well-heeled London solicitor, (Tom Wilkinson), discovers that not only is his wife having an affair with the local gentry but that she has also killed their housekeeper's husband in a hit-and-run accident. He throws up, but otherwise his stiff-upper-lip hardly quavers.<br \/><br \/>Written and directed by Julian Fellowes, who won an Oscar for writing \"Gosford Park\", (this is his directorial debut), from a novel by Nigel Balchin, it's quite comical although I am not sure how much of the comedy is intended. It's like a throw-back to British films of the forties where characters all behaved like characters in books or plays rather than like people might in real life. However, it's not all bad. Wilkinson is terrific, even if you never believe in him as a person while Emily Watson, (the adulterous wife), and Rupert Everett, (the highly amoral high-class totty), are both very good at covering the cracks in the material. Tony Pierce-Roberts' cinematography ensures that no matter how hard it is on the ear it's always good on the eye.",
        "output": "negative"
    },
    {
        "input": "The filmmaker stayed true to the most accurate account of the story published in 1894 which includes an 1846 manuscript by Richard Williams Bell (son of John and Lucy Bell and younger brother of Betsy Bell) titled \"Our Family Trouble.\" To knowledge this is the only eyewitness account ever penned. The filmmaker should be credited for accuracy but there is little to say about the production and acting quality. The acting was theatrical and the sound and picture quality was extremely poor. It appears that the filmmaker simply shot scenes of the reported events that took place without incorporating or weaving them into a flowing plot or story line. If you must know the story, read about it, its much more gripping and conclusive.",
        "output": "negative"
    },
    {
        "input": "I was able to see a preview of this movie through UCLA's pre-screening program, and let me tell you: THIS MOVIE IS UNBELIEVABLY GOOD!!!! I have seen many movies, but few have made me laugh so sincerely or talk about the movie afterward as much as this one. I had a decent respect for Tenacious D before seeing the movie, and now I am MAD about them. I will most definitely buy their album when it is released on the 14th and will see this movie again.<br \/><br \/>If you were on the fence about seeing this movie, GET OFF AND GO SEE IT!! It is worth the extremely expensive price of movie tickets these days, as you will surely bust a nut laughing during the whole thing.<br \/><br \/>Aside from the comedy, the glorious and divine music that flows from KG's guitar and JB's voice is awe inspiring. The audience is left in a stupor that such beautiful harmonies and amazing riffs can be created in conjunction with such ridiculous (and hilarious) lyrics. If for nothing other than the music itself, this movie is worth the price of admission.<br \/><br \/>With a wonderfully coherent storyline tying in almost all aspects of the traditional \"D\" history and hallmarks, great new songs, hilarious comedy, and some pretty awesome cameos, this movie ranks up there with the best! Go see it!!",
        "output": "positive"
    },
    {
        "input": "I saw The D's new film tonight at a special advance screening, and I was so blown away by its sheer greatness that I felt I had to come onto IMDb and get the word out. Admittedly, I was already a huge fan of the D's work - I loved the HBO series and listen to their music weekly (there's nothing better to sing along to), but this appreciation actually made me more apprehensive going into to tonight's screening (for we've all been disappointed one time or another by something we love when it attempted to make the jump to the big screen). With Tenacious D's \"The Pick of Destiny,\" this is not the case.<br \/><br \/>Simply put, this film rocks harder than anything I've seen and is funnier and more majestic than anything Peter Jackson, Pixar, and Will Ferrell together could produce. It tells the story of the D before we came to know them, setting up intriguing histories of Kage and Jables' upbringings, their comings together, and how they were inspired to write songs about such things as Lee, Sasquatch, and Dio. Most importantly, they reveal the true inspiration to the Greatest Song In The World, \"Tribute,\" and how it came to be (which is different than the HBO Series' version). After you've witnessed it you probably won't be able to remember it (hence the Tribute), but your mind forever be changes by its genius.<br \/><br \/>I don't go out to movies very often anymore due to the high ticket price and the hassle of getting parking, paying outrageous concession prices, etc., but I usually make exceptions when it's starring someone I really love or concerning something of the the same variety. \"The Pick of Destiny\" was so good that I have no qualms going back to see it again when it releases nationwide, and I plan on convincing all of my friends to go, too. Last week we saw \"Borat\" and loved it, but this is honest to goodness TEN TIMES BETTER. For anyone who truly loves rock music and comedic brilliance, see this film. These guys' talent is so great you should have no hesitation supporting their cause. You will not be disappointed, and the Rock Lords will smile upon you favorably.",
        "output": "positive"
    },
    {
        "input": "I saw this movie on a fluke.I was standing on 42nd street waiting for a bus to go home and a sister started passing out free tickets for a preview of this movie.I gave it a chance not expecting much.The promotional movie posters I've seen on the subway station walls do not give this film justice at all.<br \/><br \/>The movie is about a young rocker who goes on a journey to learn the craft and art of heavy metal.I'll leave it there.The movie is a heavy comedy and lot's of fun.If your are old enough to remember when Heavy Metal dominated the music scene in the eighties you are going to love this film.Jack Black is an amazingly talented comedian and actor and assuming he really wrote and performed the songs in this film he is also a talented musician.<br \/><br \/>Tenacious D is definitely worth a look!",
        "output": "positive"
    },
    {
        "input": "A wonder. My favorite film. The most important film about relationships ever made. Brilliant writing. Magnificent directing. Image systems and symbolism that leave you thinking about it all days, weeks, years later. Wow. A truly great work of art.",
        "output": "positive"
    },
    {
        "input": "Just saw it at as closing film of Austin Film Festival. Going in, a had seen a few snippets of their act at Alamo Drafthouse, and thought the trailer was amusing but I wasn't expecting such an epic theme music and the use of tarot cards is genius in the title sequence. Watch out for cameos from Ben Stiller and Tim Robbins, and the dark lord himself (who has a fetish for KG). So much over-the-top fun and the songs are so catchy. The car chase was by far my favorite scene. I know this will earn cult status right away and win over some new Tenacious D fans, just like me. I hope this does well in the theaters. \"Follow me, we are the shadows\"",
        "output": "positive"
    },
    {
        "input": "I love a film that mixes edge-of-the-seat suspense, laughs, style, good acting, and a bit of self-parody. Hitchcock consistently carried this off, and in \"Le Cercle rouge\" Jean-Pierre Melville does the same. I was sorry when this long film ended. <br \/><br \/>I agree with the English commenter who found remarks by one of my compatriots chauvinistic. I love French films, Italian films, English films, Indian films--and the increasingly rare good American films. I also feel the writer who panned the film for being not even a good copy of an American gangster film, missed the point completely. But I guess it's like jazz: either you get it, or you don't, so why waste time trying to explain.<br \/><br \/>Just see \"Le Cercle noir\" and be prepared to be deliciously entertained.",
        "output": "positive"
    },
    {
        "input": "There were heist movies before this one, and indeed the likes of Rififi were an obvious influence on it - but The Red Circle is more than just another entry in an overpopulated genre and with this film, director Jean-Pierre Melville has managed to create something that both thrills on the surface and gives its audience something to think about. Being cool is just as important a feature of the modern crime movie as guns and gangsters, and Melville delivers that with this film in droves",
        "output": "positive"
    },
    {
        "input": "After 30+ years of hiatus, once again I immerse myself in the mist of uplifting melancholy. The cold, slow-paced and existential treatment of this crime story comes from a different world, Melville's world, where darkness is pure enlightenment.",
        "output": "positive"
    },
    {
        "input": "Meville's caper film is not as good as his most famous movie, the deliciously stylish \"Le Samourai (1968).\" I don't even think this is the best example of the much-loved heist subgenre. The main thing against the film is its long running time. Meville has this tendency of concentrating on too many trivial details. He could have told the same story in a relative short time, but for reasons that I don't understand, the film seems to go on and on. Still, the movie is never boring. Melville's direction impressed me and the cast is very good, especially Alain Delon as a very \"cool\" master thief. The movie's must-see color photography is a great asset and Melville uses sound (or lack of sound) in a very effective manner. From a technical standpoint, the movie is practically flawless. At times, one gets the feeling that Meville is merely showing off, but when someone is as talented as he is, one has little reason to complain. I still like other heist movies a little bit more (Jules Dassin's \"Topkapi (1964),\" just to name one), but there is no denying that this film is a good piece of pulp entertainment and a good example of what people refer to as \"cool\" cinema.",
        "output": "positive"
    },
    {
        "input": "All men are guilty, says the chief of the police. \"They're born innocent but it doesn't last.\" Add this bit of nihilism to Jean-Pierre Melville's fascination with the idea of the crook's code of honor and you have Le Cercle Rouge. This code of honor among crooks, however, is not simply a cliché",
        "output": "positive"
    },
    {
        "input": "Jean-Pierre Melville's Le Cercle Rouge follows the lives of two criminals: Vogel (Gian Maria Volontè), a murderer who gives the cops the slip while he's being transferred from one city to another by train",
        "output": "positive"
    }
]


function gpuTrain() {
    const net = new NeuralNetworkGPU();



    net.train(xorTrainingData, { iterations: 100, log: true });

    //console.log(net.run([0, 0]));
    //console.log(net.run([0, 1]));
    //console.log(net.run([1, 0]));
    //console.log(net.run([1, 1]));

}


document.getElementById('Train-NN-GPU').addEventListener('click', gpuTrain)